### ISSUE TITLE
fastq2bam - flexibility with barcode/read lengths

### ISSUE THREAD

**Issue by anjaf** [nunofonseca/fastq_utils#1]
Hi Nuno, 

We discovered a few cases of 10x experiments, where the R1 and R2 reads don't have the expected lengths. While it isn't a problem if the reads are longer (I guess the extra bases are simply disregarded during the conversion), the fastq2bam conversion fails if the reads are shorter than expected. 

Here is one example of a 10X2 library sequenced with non-standard parameters:
Cell barcode offset = 0
Cell barcode size =16
UMI barcode offset = 16
UMI barcode size =9

Do you think it will be possible to pass these numbers as parameters if they are non-default? Or can you think of another workaround to make the script generate BAM files for this library? 

Many thanks for looking into this.
Anja

**Comment by nunofonseca** [comment]
Hi Anja,

If I understood you would like to be able to override the offset and size of cell/barcode.  

Did you have in mind something like

fastq2bam -s 10xV2 -1 a.fastq -2 b.fastq -3 c.fastq -b t.bam -c 0 -C 16 -u 16 -U 9

where 
- cell barcode offset if overridden with the value passed in -c
- cell barcode size if overridden with the value passed in -C
- UMI barcode offset if overridden with the value passed in -u
- UMI barcode offset if overridden with the value passed in -U
Cheers.

**Comment by anjaf** [comment]
Yes, I think this would work. The same might happen for sample barcode and cDNA read, so these should be adjustable too. I hope those are rare cases though. 
Would it work in a way that when there are none of these arguments given, the default value will be used?

**Comment by nunofonseca** [comment]
OK, I added the following options:
 -c int : cell barcode offset
 -C int : cell barcode size
 -u int : UMI barcode offset
 -U int : UMI barcode size
 -s int : sample barcode offset
 -S int : sample barcode size
If these parameters are not passed then the default values are used. I did not include the option for the cDNA read because it would involve much more work - we may revisit this in the future if it is really necessary. Please check the new version (0.18.0) and reopen the issue if you encounter any problem.
Cheers.

**Comment by Ahmed-Gemmy** [comment]
Hi,
